name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint with flake8
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt 
          pip install flake8 flake8-docstrings

      - name: Debug Python
        run: |
          python --version
          pip --version

      - name: run flake8
        run: | 
          flake8 src/ \
          --max-line-length=150 \
          --exclude=__pycache__, .git \
          --statistics \
          --count